cmake_minimum_required(VERSION 3.15)
project(mik64_config_manager)
if(NOT TARGET mik64_config_manager)
    add_subdirectory(lib/mik64_logger)
    file(GLOB CONFIG_SOURCES "cpp/*.cpp")
    add_library(mik64_config_manager STATIC ${CONFIG_SOURCES})
    add_library(mik64::config-manager ALIAS mik64_config_manager)
    target_include_directories(mik64_config_manager PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/h)
    target_compile_features(mik64_config_manager PRIVATE cxx_std_17)

    target_link_libraries(mik64_config_manager PRIVATE mik64::logger)
endif()
add_executable(config_manager_test main.cpp)
target_link_libraries(config_manager_test PRIVATE mik64::config-manager)
